### ISSUE TITLE
Where is the CanvasRenderer fallback?

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/ed_gui_server#5]
@reinzor

**Comment by reinzor** [comment]
Ja, sorry heb ik verwijderd. Mag terug maar was een beetje aan het spelen
met die canvas die we al hadden. En die chille lint van jou werkte al niet
mee ;)

-Rein

**Comment by Rayman** [comment]
Fixed in 53e9727645d399ac7a36d8c76ae9460b52e6e23f
